### PR TITLE
Add support for multi-channel tracks, automatically send all channels

### PR DESCRIPTION
**Pull request by kronihias**
- Mixbus and Solobus will automatically be set to maximum number of channels of any track
- All channels are sent to Mix/Solo, before it was Stereo only so you'd have to manually adjust for sending all channels

### CODE REVIEW

**Comment by ak5k** [comment]
Maybe sending all channels as default behaviour is not desireable in non-multichannel production environments? I haven't tested this, but wouldn't including all channels also include possible sidechaining sources etc? You taking interested in the project is greatly appreciated. Thank you.

**Comment by kronihias** [comment]
Thanks, this project is a game changer for live usage for me. I wanted to do something like this for a long time, thanks for starting it :)

Good point, I hardly ever use side-chaining, and most people use Stereo I assume so we shouldn't break things, very true.

I work with massive multi-channel projects, in studio and live, so this feature is essential for me.

Could we ask the user about Stereo vs Multichannel, or make a dedicated action for initializing a multichannel session?
I am not sure how we would automatically distinguish whether all or just part of the channels should be sent to Mix/Solo.

**Comment by ak5k** [comment]
A dedicated multi-channel init action would probably be the best option. Feel free to implement and PR.

**Comment by kronihias** [comment]
Ok, I added the dedicated multi-channel init action.

Let me know what you think.

I will do some more testing on my side.

**Review by ak5k — APPROVED** [review]

**Pull request merged**
